/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import HL7.FrameClient_SIR_SIH;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.ImageIcon;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import nf.Examen;
import nf.Login;
import nf.Patient;
import nf.RequetesBDExamen;
import nf.RequetesBDLogin;
import nf.RequetesBDPACS;
import static nf.RequetesBDPACS.returnPACSoneExamBis;


/**
 *
 * @author em
 */
public class AffichageExamen extends javax.swing.JFrame {

    /**
     *
     */
    Patient pat;

    /**
     *
     */
    Connection conn;

    /**
     *
     */
    Login login;

    /**
     *
     */
    Login medPrescripteur;

    /**
     *
     */
    Examen examen;

    /**
     * Creates new form CompteRendu
     *
     * @param examen un examen
     * @param pat un patient
     * @param login un login
     * @param conn Connexion à la base de données
     * @throws java.sql.SQLException
     */
    public AffichageExamen(Examen examen, Patient pat, Login login, Connection conn) throws SQLException {
        this.pat = pat;
        this.conn = conn;
        this.login = login;
        this.examen = examen;

        initComponents();

        proDetails.setText(login.getLogin().strip()
                + " - " + login.getLastName().strip()
                + " " + login.getFirstName().strip()
        );

        ImageIcon icone = new ImageIcon("src/img_icon/user_1.png");
        java.awt.Image img = icone.getImage();
        java.awt.Image newImg = img.getScaledInstance(userIcon.getWidth(), userIcon.getHeight(), java.awt.Image.SCALE_SMOOTH);
        icone = new ImageIcon(newImg);
        userIcon.setIcon(icone);

        ImageIcon iconeLogo = new ImageIcon("src/img_icon/logo.png");
        java.awt.Image imgLogo = iconeLogo.getImage();
        java.awt.Image newImgLogo = imgLogo.getScaledInstance(logoIcon.getWidth(), logoIcon.getHeight(), java.awt.Image.SCALE_SMOOTH);
        iconeLogo = new ImageIcon(newImgLogo);
        logoIcon.setIcon(iconeLogo);

        ImageIcon iconeDeconnection = new ImageIcon("src/img_icon/deconnexion.png");
        java.awt.Image imgDeconnection = iconeDeconnection.getImage();
        java.awt.Image newImgDeconnection = imgDeconnection.getScaledInstance(deconnexionButton.getHeight(), deconnexionButton.getHeight(), java.awt.Image.SCALE_SMOOTH);
        iconeDeconnection = new ImageIcon(newImgDeconnection);
        deconnexionButton.setIcon(iconeDeconnection);

        ImageIcon iconeRetour = new ImageIcon("src/img_icon/retour.png");
        java.awt.Image imgRetour = iconeRetour.getImage();
        java.awt.Image newImgRetour = imgRetour.getScaledInstance(retourButton.getHeight(), retourButton.getHeight(), java.awt.Image.SCALE_SMOOTH);
        iconeRetour = new ImageIcon(newImgRetour);
        retourButton.setIcon(iconeRetour);

        ImageIcon iconePatient = new ImageIcon("src/img_icon/health-report.png");
        java.awt.Image imgPatient = iconePatient.getImage();
        java.awt.Image newImgPatient = imgPatient.getScaledInstance(patientIcon.getHeight(), patientIcon.getHeight(), java.awt.Image.SCALE_SMOOTH);
        iconePatient = new ImageIcon(newImgPatient);
        patientIcon.setIcon(iconePatient);

        patientIdField.setText(pat.getPatientId());
        lastNamePField.setText(pat.getLastNameP());
        firstNamePField.setText(pat.getFirstNameP());
        birthDateField.setText(pat.getBirthDate());
        genderCheckBox.setSelected(true);
        genderCheckBox.setText(pat.getGender());
        examDateField.setText(this.examen.getDateExam().substring(0, 16));
        typeExamField.setText(this.examen.getTypeExamen());
        this.medPrescripteur = null;

        CRTextArea.setText("");
        String[] idPACS = RequetesBDPACS.returnPACSoneExam(examen.getExamId(), conn);
        listImg.setListData(idPACS);

        saveCRButton.setVisible(false);
        CRTextArea.setEditable(false);

        try {
            // TODO add your handling code here:
            if (RequetesBDLogin.idPH(login.getLogin(), conn)) {
                editionCRButton.setVisible(false);
                CRTextArea.setText(examen.getReport());
            }
        } catch (SQLException ex) {
            Logger.getLogger(AccesListeExamen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println("Date1: "+this.examen.getDateExam());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CRTextArea = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        editionCRButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        proDetails = new javax.swing.JTextField();
        retourButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        logoIcon = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        deconnexionButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listImg = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        patientIconPanel = new javax.swing.JPanel();
        patientIcon = new javax.swing.JLabel();
        patientIdField = new javax.swing.JTextField();
        lastNamePField = new javax.swing.JTextField();
        firstNamePField = new javax.swing.JTextField();
        examDateField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        birthDateField = new javax.swing.JTextField();
        genderCheckBox = new javax.swing.JCheckBox();
        typeExamField = new javax.swing.JTextField();
        showImgButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        observationArea = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        saveCRButton = new javax.swing.JButton();
        viewAllImg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1490, 794));
        jPanel2.setMinimumSize(new java.awt.Dimension(1490, 794));
        jPanel2.setPreferredSize(new java.awt.Dimension(1490, 794));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        CRTextArea.setColumns(20);
        CRTextArea.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        CRTextArea.setRows(5);
        jScrollPane1.setViewportView(CRTextArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 153, 153));
        jTextField3.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(242, 236, 234));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Compte rendu");
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.cyan, null, java.awt.Color.cyan));

        editionCRButton.setBackground(new java.awt.Color(255, 255, 255));
        editionCRButton.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        editionCRButton.setForeground(new java.awt.Color(51, 51, 51));
        editionCRButton.setText("Edition CR");
        editionCRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editionCRButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(242, 236, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        proDetails.setEditable(false);
        proDetails.setBackground(new java.awt.Color(255, 255, 255));
        proDetails.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        proDetails.setForeground(new java.awt.Color(0, 0, 0));
        proDetails.setText("PH01 - DURAND Bastien");
        proDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.blue, null, java.awt.Color.white));
        proDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proDetailsActionPerformed(evt);
            }
        });

        retourButton.setBackground(new java.awt.Color(255, 255, 255));
        retourButton.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        retourButton.setForeground(new java.awt.Color(0, 153, 255));
        retourButton.setText("Retour");
        retourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Détails examen");

        jLabel3.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Health IT");

        logoPanel.setBackground(new java.awt.Color(242, 236, 234));

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        userPanel.setBackground(new java.awt.Color(242, 236, 234));

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        deconnexionButton.setBackground(new java.awt.Color(255, 255, 255));
        deconnexionButton.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        deconnexionButton.setForeground(new java.awt.Color(0, 153, 255));
        deconnexionButton.setText("Se déconnecter");
        deconnexionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274)
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deconnexionButton)
                        .addGap(18, 18, 18)
                        .addComponent(retourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(proDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(proDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(retourButton)
                            .addComponent(deconnexionButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        listImg.setBackground(new java.awt.Color(255, 255, 255));
        listImg.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        listImg.setForeground(new java.awt.Color(0, 153, 255));
        listImg.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Radio 1", "Radio 2", "Radio 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listImg.setSelectionBackground(new java.awt.Color(0, 204, 204));
        jScrollPane2.setViewportView(listImg);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        jTextField5.setText("Identifiant :");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(102, 102, 102));
        jTextField6.setText("Nom :");
        jTextField6.setBorder(null);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(102, 102, 102));
        jTextField7.setText("Date d'examen :");
        jTextField7.setBorder(null);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Prénom :");

        patientIconPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout patientIconPanelLayout = new javax.swing.GroupLayout(patientIconPanel);
        patientIconPanel.setLayout(patientIconPanelLayout);
        patientIconPanelLayout.setHorizontalGroup(
            patientIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        patientIconPanelLayout.setVerticalGroup(
            patientIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        patientIdField.setEditable(false);
        patientIdField.setBackground(new java.awt.Color(255, 255, 255));
        patientIdField.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        patientIdField.setForeground(new java.awt.Color(51, 51, 51));
        patientIdField.setText("PAT01");
        patientIdField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patientIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdFieldActionPerformed(evt);
            }
        });

        lastNamePField.setEditable(false);
        lastNamePField.setBackground(new java.awt.Color(255, 255, 255));
        lastNamePField.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        lastNamePField.setForeground(new java.awt.Color(51, 51, 51));
        lastNamePField.setText("BROUILLARD");
        lastNamePField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lastNamePField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNamePFieldActionPerformed(evt);
            }
        });

        firstNamePField.setEditable(false);
        firstNamePField.setBackground(new java.awt.Color(255, 255, 255));
        firstNamePField.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        firstNamePField.setForeground(new java.awt.Color(51, 51, 51));
        firstNamePField.setText("Jean");
        firstNamePField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        examDateField.setEditable(false);
        examDateField.setBackground(new java.awt.Color(255, 255, 255));
        examDateField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        examDateField.setForeground(new java.awt.Color(51, 51, 51));
        examDateField.setText("2016-06-11 20:05:58.0");
        examDateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        examDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examDateFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Date de naissance :");

        birthDateField.setEditable(false);
        birthDateField.setBackground(new java.awt.Color(255, 255, 255));
        birthDateField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        birthDateField.setForeground(new java.awt.Color(51, 51, 51));
        birthDateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        genderCheckBox.setText("jCheckBox1");
        genderCheckBox.setEnabled(false);

        typeExamField.setEditable(false);
        typeExamField.setBackground(new java.awt.Color(0, 153, 153));
        typeExamField.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        typeExamField.setForeground(new java.awt.Color(242, 236, 234));
        typeExamField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        typeExamField.setText("RADIO");
        typeExamField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.cyan, null, java.awt.Color.cyan));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(patientIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(typeExamField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(examDateField)
                            .addComponent(birthDateField)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNamePField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNamePField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(genderCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(patientIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(typeExamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNamePField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(firstNamePField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(birthDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        showImgButton.setBackground(new java.awt.Color(255, 255, 255));
        showImgButton.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        showImgButton.setForeground(new java.awt.Color(51, 51, 51));
        showImgButton.setText("Visionner image");
        showImgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showImgButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        observationArea.setBackground(new java.awt.Color(255, 255, 255));
        observationArea.setColumns(20);
        observationArea.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        observationArea.setForeground(new java.awt.Color(51, 51, 51));
        observationArea.setRows(5);
        jScrollPane4.setViewportView(observationArea);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );

        jTextField2.setBackground(new java.awt.Color(0, 153, 153));
        jTextField2.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Observations");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        saveCRButton.setBackground(new java.awt.Color(255, 255, 255));
        saveCRButton.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        saveCRButton.setForeground(new java.awt.Color(51, 51, 51));
        saveCRButton.setText("Enregistrer CR");
        saveCRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCRButtonActionPerformed(evt);
            }
        });

        viewAllImg.setBackground(new java.awt.Color(255, 255, 255));
        viewAllImg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewAllImg.setForeground(new java.awt.Color(0, 0, 0));
        viewAllImg.setText("Visionner toutes les images");
        viewAllImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewAllImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showImgButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editionCRButton)
                        .addGap(27, 27, 27)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(132, 132, 132)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(saveCRButton)
                        .addGap(86, 86, 86)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 279, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saveCRButton))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showImgButton)
                            .addComponent(editionCRButton))
                        .addGap(7, 7, 7)
                        .addComponent(viewAllImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 117, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1502, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proDetailsActionPerformed

    private void retourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourButtonActionPerformed
        // TODO add your handling code here:
        AccesListeExamen accesListeExamen = null;

        try {
            System.out.println("Date2: "+this.examen.getDateExam());
            accesListeExamen = new AccesListeExamen(this.login, this.pat, conn);
        } catch (SQLException ex) {
            Logger.getLogger(AffichageExamen.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setVisible(false);
        accesListeExamen.setVisible(true);
        accesListeExamen.setLocationRelativeTo(null);
    }//GEN-LAST:event_retourButtonActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void deconnexionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionButtonActionPerformed
        // TODO add your handling code here:
        int retour = JOptionPane.showConfirmDialog(this, "Etes-vous sur de vouloir vous déconnecter ? ", "", JOptionPane.YES_NO_OPTION);
        System.out.println("retour= " + retour);
        if (retour == 0) {
            Connexion connexion = null;
            try {
                System.out.println("Date3: "+this.examen.getDateExam());
                connexion = new Connexion();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(PageAccueil.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
            connexion.setVisible(true);
            connexion.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_deconnexionButtonActionPerformed

    private void patientIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdFieldActionPerformed

    private void lastNamePFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNamePFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNamePFieldActionPerformed

    private void examDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examDateFieldActionPerformed

    private void editionCRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editionCRButtonActionPerformed
        CRTextArea.setEditable(true);
        saveCRButton.setVisible(true);
        editionCRButton.setVisible(false);
        try {
            System.out.println("Date4: "+this.examen.getDateExam());
            RequetesBDExamen.updateStatusExam(this.examen.getExamId(), this.conn);
        } catch (SQLException ex) {
            Logger.getLogger(AffichageExamen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_editionCRButtonActionPerformed

    /**
     *
     * @param medPrescripteur
     * @param realisationMedecin
     * @return
     * @throws SQLException
     */
    public String initializeReport(Login medPrescripteur, Login realisationMedecin) throws SQLException {
        String str = this.examen.getTypeExamen() + "------------------------------------------- \n"
                + "\tCompte-rendu rédigé par " + this.login.getLastName().trim() + " - " + this.login.getFirstName().trim()
                + "\n\tNombre d'images enregistree(s): " + RequetesBDPACS.returnNbImgOneExam(examen.getExamId(), conn)
                + "\n\tDate de l'examen: " + this.examen.getDateExam().substring(0, 16)
                + "\n------------------------------------------------------"
                + "\n COMPTE RENDU:\n";
        System.out.println("Date5: "+this.examen.getDateExam());
        return str;

    }
//    public String initializeReport(Login medPrescripteur, Login realisationMedecin) throws SQLException {
//        String str = "------------------------------------------- \n"
//                + "\t" + Login.infoMedCR(medPrescripteur)
//                + "\n\tNombre d'images enregistrees: " + RequetesBDPACS.returnNbImgOneExam(examen.getExamId(), conn)
//                + "\n------------------------------------------------------"
//                + "\n COMPTE RENDU:\n";
//        return str;
//
//    }

    private void showImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showImgButtonActionPerformed
        // TODO add your handling code here:
        int pacsIdSelected = selectImgList();
        try {
            byte[] imgSelected = RequetesBDPACS.showImage(pacsIdSelected, conn);
            Image img = Toolkit.getDefaultToolkit().createImage(imgSelected);
            ImageIcon icone = new ImageIcon(img);
            java.awt.Image imgIcone = icone.getImage();
            java.awt.Image newImg = imgIcone.getScaledInstance(imgLabel.getWidth(), imgLabel.getHeight(), java.awt.Image.SCALE_SMOOTH);
            icone = new ImageIcon(newImg);
            imgLabel.setIcon(icone);

            String comments = RequetesBDPACS.returnCommentsImg(pacsIdSelected, conn);
            if (comments != null) {
                observationArea.setText(comments);
            }

        } catch (SQLException ex) {
            Logger.getLogger(AffichageExamen.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_showImgButtonActionPerformed

    private void saveCRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCRButtonActionPerformed
        int retour = JOptionPane.showConfirmDialog(this, "Etes-vous sur de vouloir enregistrer ce compte-rendu ? ", "", JOptionPane.YES_NO_OPTION);
        System.out.println("retour= " + retour);
        if (retour == 0) {

            try {
                // TODO add your handling code here:
                //this.examen.setReport(CRTextArea.getText());
                System.out.println("Date6: "+this.examen.getDateExam());
                System.out.println("report to save:  " + CRTextArea.getText());
                this.examen.setReport(this.initializeReport(this.medPrescripteur, login) + CRTextArea.getText().trim());
                RequetesBDExamen.updateCR(this.examen.getExamId(), this.examen.getReport(), conn);
                if (RequetesBDExamen.isPatientSIH(this.pat.getPatientId(), conn)) {
                    FrameClient_SIR_SIH clientSIH = new FrameClient_SIR_SIH(this.examen, this.pat, this.conn);
                    clientSIH.setVisible(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(AffichageExamen.class.getName()).log(Level.SEVERE, null, ex);
            }
            CRTextArea.setText(examen.getReport());
            saveCRButton.setVisible(false);
        }
    }//GEN-LAST:event_saveCRButtonActionPerformed

    private void viewAllImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllImgActionPerformed
        System.out.println("Date6: "+this.examen.getDateExam());
        int nbImg = 0;
        String[] idPacs = null;
        try {
            idPacs = returnPACSoneExamBis(this.examen.getExamId(), conn);
        } catch (SQLException ex) {
            Logger.getLogger(AffichageExamen.class.getName()).log(Level.SEVERE, null, ex);
        }

        nbImg = idPacs.length;

        JFrame allImg = new JFrame(this.examen.getDateExam() + this.pat.getLastNameP() + " " + this.pat.getFirstNameP());
        allImg.setSize(800, 800);
        allImg.setResizable(false);
        JPanel panelImg = new JPanel();

        int height = 0;
        if (nbImg % 2 != 0) {
            height = (nbImg + 1) / 2;
            panelImg.setLayout(new GridLayout(((nbImg + 1) / 2), 2, 3, 3));
        } else {
            height = (nbImg) / 2;
            panelImg.setLayout(new GridLayout((nbImg / 2), 2, 3, 3));
        }

        for (int i = 0; i < nbImg; i++) {
            JLabel temp = new JLabel();
            try {

                byte[] imgSelected = RequetesBDPACS.showImage(Integer.parseInt(idPacs[i]), conn);
                Image img = Toolkit.getDefaultToolkit().createImage(imgSelected);
                ImageIcon icone = new ImageIcon(img);
                java.awt.Image imgIcone = icone.getImage();
                java.awt.Image newImg = imgIcone.getScaledInstance(allImg.getWidth() / 2, allImg.getHeight() / 2, java.awt.Image.SCALE_SMOOTH);
                icone = new ImageIcon(newImg);
                temp.setIcon(icone);

            } catch (SQLException ex) {
                Logger.getLogger(AffichageExamen.class.getName()).log(Level.SEVERE, null, ex);
            }
            panelImg.add(temp);
        }
        JScrollPane jsp = new JScrollPane(panelImg);
        allImg.add(jsp);
        allImg.setVisible(true);
        allImg.setLocationRelativeTo(null);

    }//GEN-LAST:event_viewAllImgActionPerformed

    /**
     *
     * @return
     */
    public int selectImgList() {
        System.out.println("Date7: "+this.examen.getDateExam());
        String selectedImg = listImg.getSelectedValue();
        System.out.println("listImg.getSelectedValue()=" + listImg.getSelectedValue());
        String[] selectedImgSplit = selectedImg.split(" ");
        String idImg = selectedImgSplit[1];
        System.out.println("pacsId selected= " + idImg);
        int selectedId = Integer.parseInt(idImg);
        return selectedId;

    }

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AffichageExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AffichageExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AffichageExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AffichageExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AffichageExamen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CRTextArea;
    private javax.swing.JTextField birthDateField;
    private javax.swing.JButton deconnexionButton;
    private javax.swing.JButton editionCRButton;
    private javax.swing.JTextField examDateField;
    private javax.swing.JTextField firstNamePField;
    private javax.swing.JCheckBox genderCheckBox;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField lastNamePField;
    private javax.swing.JList<String> listImg;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JTextArea observationArea;
    private javax.swing.JLabel patientIcon;
    private javax.swing.JPanel patientIconPanel;
    private javax.swing.JTextField patientIdField;
    private javax.swing.JTextField proDetails;
    private javax.swing.JButton retourButton;
    private javax.swing.JButton saveCRButton;
    private javax.swing.JButton showImgButton;
    private javax.swing.JTextField typeExamField;
    private javax.swing.JLabel userIcon;
    private javax.swing.JPanel userPanel;
    private javax.swing.JButton viewAllImg;
    // End of variables declaration//GEN-END:variables
}
